language: rust

rust:
    - stable
    - beta
    - nightly

jobs:
    allow_failures:
        - rust: nightly
    fast_finish: true

before_script:
    - make config

script:
    - make ci
    - make run

deploy:
- provider: script
  skip_cleanup: true
  script: make publish
  on:
    tags: true
    rust: stable
    condition: $TRAVIS_OS_NAME = linux